### ISSUE TITLE
Low battery warning If I use "uncapped GPU" mode in handheld

### ISSUE THREAD

**Issue by pitrako** [jope82/sys-clk-uncapped-gpu-and-other-extras#2] opened 2021-10-21 12:17 UTC
The switch has more battery than the red low battery icon that appears in the middle of the screen says but it enters sleep mode anyway, if i disable "uncapped GPU" mode i can play normally. I tried spoof profiles but with the same results. It happens at 70% battery remaining.

I have hekate 5.6.3 and Atmosphere 1.1.1.

**Comment by jope82** [comment] 2021-10-21 19:34
I think you are just pushing it too much in handheld, the battery drain is too much for Switch to handle. For example GPU = 921 seems to be too much in handheld, NS will enter sleep mode because the battery drain is so high. I think this behaviour is built into the Switch and can’t be circumvented. If someone knows otherwise please let me know.

**Comment by pitrako** [comment] 2021-10-22 07:36
Yes you are right, i tried 768, 844 and 921 oc, with 921 it happens inmediately after certain % of battery remaining (in super mario 3d world the switch does it when in the title before loading a save), 768 and 844 almost the same, i didn't try 691, 614 and 537 but the default 460 seems the only stable option.

**Comment by jope82** [comment] 2021-10-22 13:36
Hmm, definitely something wrong with your Switch if default docked GPU 768 does not work in handheld. I can easily run CPU = 1224 + GPU = 768 + MEM = 2133 (patched) in handheld for example in Super Mario 3D World and BOTW. Maybe your battery is dying?

**Comment by pitrako** [comment] 2021-10-22 17:17
I don't know, the only thing i forgot to tell was that i was using docked mode with reversenx in handheld, docked mode spends battery faster, i let my switch rest and know it's at 1785 CPU, 768 GPU and 1600 MEM and right know it's not doing it.

**Comment by jope82** [comment] 2021-10-22 18:11
Yep, with ReverseNX Bowser's Fury is 60 FPS with better resolution so even more battery strain with that. But still I can run CPU = 1224 + GPU = 768 + MEM = 2133 in Bowser's Fury in handheld with 'docked' set in ReverseNX. Upping GPU to 921 will make Switch sleep instantly :).

But anyway it's not a bug in sys-clk (until proven otherwise) so I'm closing this.

**Closed as completed by jope82** 2021-10-22 18:11 UTC
